Revert Logback to v1.1.3
Since Logback 1.1.4, SLF4J minimum required version is 1.7.16.
There is a lot of code out there in the Maven ecosystem which used older versions.

In rare cases it can fail (extracted from http://logback.qos.ch/news.html):

    February 11th, 2016, Release of version 1.1.4

    Logback 1.1.4 requires SLF4J version 1.7.16 or later.

    Added event replay support as introduced in SLF4J version 1.7.15. In most circumstances, logack-classic should run fine with earlier versions of slf4j-api, including all versions in the 1.6.x and 1.7.x series. However, with a version of slf4j-api.jar earlier than 1.7.15 in the classpath, attempting introspection of a Logger instance will result in a NoClassDefFoundError similar to that shown below.

    Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/event/LoggingEvent
            at java.lang.Class.getDeclaredMethods0(Native Method)
            at java.lang.Class.privateGetDeclaredMethods(Class.java:2451)
            at java.lang.Class.privateGetPublicMethods(Class.java:2571)
            at java.lang.Class.getMethods(Class.java:1429)
            at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1261)
            at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1122)
            at java.beans.Introspector.getBeanInfo(Introspector.java:414)
            at java.beans.Introspector.getBeanInfo(Introspector.java:161)

Fixes #24 and Fixes https://github.com/jcgay/homebrew-jcgay/issues/2